// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwcQn2-yGEapDpvLytzngXNo-uEYenXE',
    appId: '1:519292716504:web:f829106b0a85b4f909dead',
    messagingSenderId: '519292716504',
    projectId: 'fir-test-eab9a',
    authDomain: 'fir-test-eab9a.firebaseapp.com',
    storageBucket: 'fir-test-eab9a.appspot.com',
    measurementId: 'G-6YPZDKZVTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPCY_EHhbkcKLiTKflLLTyVKHjfemijo',
    appId: '1:519292716504:android:ff3def74c283675409dead',
    messagingSenderId: '519292716504',
    projectId: 'fir-test-eab9a',
    storageBucket: 'fir-test-eab9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoyPKYEpuNfT-H3PyvpRHJ4B_Oqd9JiAU',
    appId: '1:519292716504:ios:6b15d4e58f13f1e809dead',
    messagingSenderId: '519292716504',
    projectId: 'fir-test-eab9a',
    storageBucket: 'fir-test-eab9a.appspot.com',
    iosClientId: '519292716504-6e78jjksi6jdmq8aspki59av47hcb3vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoyPKYEpuNfT-H3PyvpRHJ4B_Oqd9JiAU',
    appId: '1:519292716504:ios:6b15d4e58f13f1e809dead',
    messagingSenderId: '519292716504',
    projectId: 'fir-test-eab9a',
    storageBucket: 'fir-test-eab9a.appspot.com',
    iosClientId: '519292716504-6e78jjksi6jdmq8aspki59av47hcb3vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
